In [17]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler,RobustScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import cross_val_score,cross_val_predict
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 

In [18]:
data=pd.read_csv('F:/Python Programs/DataSets/breast_cancer.csv')

In [34]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave_points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [20]:
data.drop(['id'],axis=1,inplace=True)

In [37]:
data['diagnosis']=pd.get_dummies(data['diagnosis'])

In [39]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          0        17.99         10.38          122.80     1001.0   
1          0        20.57         17.77          132.90     1326.0   
2          0        19.69         21.25          130.00     1203.0   
3          0        11.42         20.38           77.58      386.1   
4          0        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave_points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [40]:
features=data.iloc[:,1:].copy()
label=data.iloc[:,0].copy()

In [41]:
features.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave_points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave_points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [53]:
x_train, x_test, y_train, y_test = train_test_split(features,label,test_size=0.33,random_state=2)

#create KNN classifier
knn= KNeighborsClassifier(n_neighbors=3)

rs1=RobustScaler()
x_train=rs1.fit_transform(x_train)
#sc1=StandardScaler()
#x_train=sc1.fit_transform(x_train)

#Train the model using the training sets
knn.fit(x_train,y_train)

rs2=RobustScaler()
x_test=rs2.fit_transform(x_test)

#sc2=StandardScaler()
#x_test=sc2.fit_transform(x_test)

#Predict the response for test dataset
y_pred = knn.predict(x_test)
#confusion matrix
conf_mat= confusion_matrix(y_test,y_pred) 
print("\nConfusion Matrix : \n",conf_mat)

#classification report
print("\nClassification Report :\n",classification_report(y_test,y_pred))
scores=cross_val_score(KNeighborsClassifier(),features,label,cv=5)
print('cross validation score : ',scores.mean())


Confusion Matrix : 
 [[ 70   3]
 [  2 113]]

Classification Report :
               precision    recall  f1-score   support

           0       0.97      0.96      0.97        73
           1       0.97      0.98      0.98       115

    accuracy                           0.97       188
   macro avg       0.97      0.97      0.97       188
weighted avg       0.97      0.97      0.97       188

cross validation score :  0.9279459711224964


In [54]:
from sklearn.naive_bayes import GaussianNB
x_train, x_test, y_train, y_test = train_test_split(features,label,test_size=0.33,random_state=2)
classifier=GaussianNB()

rs1=RobustScaler()
x_train=rs1.fit_transform(x_train)

#sc1=StandardScaler()
#x_train=sc1.fit_transform(x_train)

classifier.fit(x_train,y_train)

rs2=RobustScaler()
x_test=rs2.fit_transform(x_test)

#sc2=StandardScaler()
#x_test=sc2.fit_transform(x_test)

y_pred=classifier.predict(x_test)

conf_mat= confusion_matrix(y_test,y_pred) 
print("\nConfusion Matrix : \n",conf_mat)

#classification report
print("\nClassification Report :\n",classification_report(y_test,y_pred))
print('cross validation score : ',cross_val_score(GaussianNB(),features,label,cv=5).mean())


Confusion Matrix : 
 [[ 66   7]
 [  5 110]]

Classification Report :
               precision    recall  f1-score   support

           0       0.93      0.90      0.92        73
           1       0.94      0.96      0.95       115

    accuracy                           0.94       188
   macro avg       0.93      0.93      0.93       188
weighted avg       0.94      0.94      0.94       188

cross validation score :  0.9385188635305075


In [58]:
from sklearn.tree import DecisionTreeClassifier
x_train, x_test, y_train, y_test = train_test_split(features,label,test_size=0.33,random_state=3)
classifier=DecisionTreeClassifier()

rs1=RobustScaler()
x_train=rs1.fit_transform(x_train)

#sc1=StandardScaler()
#x_train=sc1.fit_transform(x_train)

classifier.fit(x_train,y_train)

rs2=RobustScaler()
x_test=rs2.fit_transform(x_test)

#sc2=StandardScaler()
#x_test=sc2.fit_transform(x_test)

y_pred=classifier.predict(x_test)

conf_mat= confusion_matrix(y_test,y_pred) 
print("\nConfusion Matrix : \n",conf_mat)

#classification report
print("\nClassification Report :\n",classification_report(y_test,y_pred))
print('cross validation score : ',cross_val_score(DecisionTreeClassifier(),features,label,cv=5).mean())


Confusion Matrix : 
 [[ 63   5]
 [  6 114]]

Classification Report :
               precision    recall  f1-score   support

           0       0.91      0.93      0.92        68
           1       0.96      0.95      0.95       120

    accuracy                           0.94       188
   macro avg       0.94      0.94      0.94       188
weighted avg       0.94      0.94      0.94       188

cross validation score :  0.9138487812451483


In [59]:
#feature selection using chi squared---
from sklearn.feature_selection import SelectKBest,chi2
skb=SelectKBest(score_func=chi2, k=10)
fit=skb.fit(features,label)
scores=pd.DataFrame(fit.scores_,columns=['scores'])
columns=pd.DataFrame(features.columns,columns=['columns'])
columns=columns.join(scores)

In [60]:
print(columns.nlargest(10,'scores'))
new_f=list(columns.nlargest(10,'scores')['columns'])

            columns         scores
23       area_worst  112598.431564
3         area_mean   53991.655924
13          area_se    8758.504705
22  perimeter_worst    3665.035416
2    perimeter_mean    2011.102864
20     radius_worst     491.689157
0       radius_mean     266.104917
12     perimeter_se     250.571896
21    texture_worst     174.449400
1      texture_mean      93.897508


In [62]:
final_f=pd.DataFrame()
for i in new_f:
    final_f[i]=(data[i])

In [63]:
final_f.head()

area_worst  area_mean  area_se  perimeter_worst  perimeter_mean  \
0      2019.0     1001.0   153.40           184.60          122.80   
1      1956.0     1326.0    74.08           158.80          132.90   
2      1709.0     1203.0    94.03           152.50          130.00   
3       567.7      386.1    27.23            98.87           77.58   
4      1575.0     1297.0    94.44           152.20          135.10   

   radius_worst  radius_mean  perimeter_se  texture_worst  texture_mean  
0         25.38        17.99         8.589          17.33         10.38  
1         24.99        20.57         3.398          23.41         17.77  
2         23.57        19.69         4.585          25.53         21.25  
3         14.91        11.42         3.445          26.50         20.38  
4         22.54        20.29         5.438          16.67         14.34

In [68]:
x_train, x_test, y_train, y_test = train_test_split(final_f,label,test_size=0.33,random_state=3)

#create KNN classifier
classifier= KNeighborsClassifier(n_neighbors=3)

rs1=RobustScaler()
x_train=rs1.fit_transform(x_train)

#sc1=StandardScaler()
#x_train=sc1.fit_transform(x_train)

classifier.fit(x_train,y_train)

rs2=RobustScaler()
x_test=rs2.fit_transform(x_test)

y_pred = classifier.predict(x_test)
#confusion matrix
conf_mat= confusion_matrix(y_test,y_pred) 
print("\nConfusion Matrix : \n",conf_mat)

#classification report
print("\nClassification Report :\n",classification_report(y_test,y_pred))
scores=cross_val_score(KNeighborsClassifier(),final_f,label,cv=5)
print('cross validation score : ',scores.mean())


Confusion Matrix : 
 [[ 64   4]
 [  4 116]]

Classification Report :
               precision    recall  f1-score   support

           0       0.94      0.94      0.94        68
           1       0.97      0.97      0.97       120

    accuracy                           0.96       188
   macro avg       0.95      0.95      0.95       188
weighted avg       0.96      0.96      0.96       188

cross validation score :  0.9279459711224964


In [46]:
#---PCA-----
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(features,label,test_size=0.33,random_state=0)

pca=PCA(n_components=2) #initially set it to 'None' to check top scores
x_train=pca.fit_transform(x_train)
x_test=pca.fit_transform(x_test)
explained_var_ratio=list(pca.explained_variance_ratio_)

In [47]:
for i in (explained_var_ratio):
    print("%.5f"%i)
#print(explained_var_ratio)

0.45095
0.18942


In [72]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report
classifier=KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train,y_train)
pred=classifier.predict(x_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[105  16]
 [  8  59]]
              precision    recall  f1-score   support

           0       0.93      0.87      0.90       121
           1       0.79      0.88      0.83        67

    accuracy                           0.87       188
   macro avg       0.86      0.87      0.86       188
weighted avg       0.88      0.87      0.87       188



In [69]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
classifier=SVC(kernel='linear')
classifier.fit(x_train,y_train)
pred=classifier.predict(x_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[107  14]
 [  7  60]]
              precision    recall  f1-score   support

           0       0.94      0.88      0.91       121
           1       0.81      0.90      0.85        67

    accuracy                           0.89       188
   macro avg       0.87      0.89      0.88       188
weighted avg       0.89      0.89      0.89       188



In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report
classifier=LogisticRegression()
classifier.fit(x_train,y_train)
pred=classifier.predict(x_test)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[107  14]
 [  3  64]]
              precision    recall  f1-score   support

           0       0.97      0.88      0.93       121
           1       0.82      0.96      0.88        67

    accuracy                           0.91       188
   macro avg       0.90      0.92      0.90       188
weighted avg       0.92      0.91      0.91       188

